"""Shared paths for FoXYiZ pyUtils (not f/ or x/).

FOXYIZ_ROOT = parent (engine: f x y z pyUtils)
KK_ROOT     = FoXYiZ parent (qoa_web, Docs, archive)
"""

from __future__ import annotations

from pathlib import Path

FOXYIZ_ROOT = Path(__file__).resolve().parent.parent
KK_ROOT = FOXYIZ_ROOT.parent
PYUTILS_DIR = Path(__file__).resolve().parent
U_DIR = PYUTILS_DIR  # legacy alias
SUITE_QOA_WEB = FOXYIZ_ROOT / "y" / "qoa_web"
SUITE_QOA_WEB_LIVE = FOXYIZ_ROOT / "y" / "qoa_web_live"
ARCHIVE_PYUTILS = KK_ROOT / "archive" / "pyUtils_oneoff"
Z_DIR = FOXYIZ_ROOT / "z"
ARCHIVE_CLEANUP = KK_ROOT / "archive" / "cleanup"

# HTML reports generated by pyUtils scripts (not FoXYiZ z/*_zDash.html)
Y_VISUALIZATION_HTML = U_DIR / "y_visualization.html"
Z_DEFECTS_DASHBOARD_HTML = U_DIR / "zDefectsDashboard.html"
Z_BATCH_DASH_GLOB = "z/zDash_batch_*.html"
