"""Shared paths for FoXYiZ pyUtils (not f/ or x/).

FOXYIZ_ROOT = parent (engine: f x y z pyUtils)
KK_ROOT     = FoXYiZ parent (qoa_web, Docs, archive)

Frozen (FoXYiZ.exe): FOXYIZ_ROOT is the folder that contains ``y/``
(exe directory, or its parent when the exe lives under ``f/``).
"""

from __future__ import annotations

import sys
from pathlib import Path


def _resolve_foxyiz_root() -> Path:
    if getattr(sys, "frozen", False):
        exe_dir = Path(sys.executable).resolve().parent
        if (exe_dir / "y").is_dir():
            return exe_dir
        parent = exe_dir.parent
        if parent != exe_dir and (parent / "y").is_dir():
            return parent
        return exe_dir
    return Path(__file__).resolve().parent.parent


FOXYIZ_ROOT = _resolve_foxyiz_root()
KK_ROOT = FOXYIZ_ROOT.parent
FXYZ_ROOT = KK_ROOT.parent  # sibling of KK/ — large archives live here
PYUTILS_DIR = Path(__file__).resolve().parent
U_DIR = PYUTILS_DIR  # legacy alias
SUITE_QOA_WEB = FOXYIZ_ROOT / "y" / "qoa_web"
SUITE_QOA_WEB_LIVE = FOXYIZ_ROOT / "y" / "qoa_web_live"
ARCHIVE_PYUTILS = KK_ROOT / "archive" / "pyUtils_oneoff"
Z_DIR = FOXYIZ_ROOT / "z"
# Dated z/ runs → outside KK so the working tree stays lean
ARCHIVE_CLEANUP = FXYZ_ROOT / "archive" / "cleanup"

# HTML reports generated by pyUtils scripts (not FoXYiZ z/*_zDash.html)
Y_VISUALIZATION_HTML = U_DIR / "y_visualization.html"
Z_DEFECTS_DASHBOARD_HTML = U_DIR / "zDefectsDashboard.html"
Z_BATCH_DASH_GLOB = "z/zDash_batch_*.html"
