"""Shared paths for KK utilities (u/). Does not import f/ or x/."""

from __future__ import annotations

from pathlib import Path

KK_ROOT = Path(__file__).resolve().parent.parent
U_DIR = Path(__file__).resolve().parent
SUITE_QOA_WEB = KK_ROOT / "y" / "qoa_web"
Z_DIR = KK_ROOT / "z"
ARCHIVE_CLEANUP = KK_ROOT / "archive" / "cleanup"

# HTML reports generated by u/ scripts (not FoXYiZ z/*_zDash.html)
Y_VISUALIZATION_HTML = U_DIR / "y_visualization.html"
Z_DEFECTS_DASHBOARD_HTML = U_DIR / "zDefectsDashboard.html"
Z_BATCH_DASH_GLOB = "z/zDash_batch_*.html"
